apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-deployment
spec:
  selector:
    matchLabels:
      app: cliente
  replicas: 1
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
      - name: cliente
        image: thiagocostacr/cliente:latest ##repositório onde subí a imagem desse projeto
        env:
          - name: JSON_SORT_KEYS
            valueFrom:
              configMapKeyRef:
                name: clientedb-configmap
                key: JSON_SORT_KEYS
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: clientedb-configmap
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: clientedb-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clientedb-secrets
                key: password
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: clientedb-configmap
                key: MYSQL_DB
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: clientedb-configmap
                key: MYSQL_PORT
        ports:
          - containerPort: 5000
